version: '3'

services:
  shellcrash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shellcrash
    restart: unless-stopped
    ports:
      - "7890:7890"  # 客户端端口
      - "9999:9999"  # 管理面板端口
    volumes:
      - ./config/subscriptions.txt:/etc/ShellCrash/subscriptions.txt
      - shellcrash_data:/etc/ShellCrash  # 持久化数据

volumes:
  shellcrash_data:  # 定义数据卷 